import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar configuration for Rhythmix documentation
 *
 * Rhythmix is a simple yet powerful rule expression engine for stream data processing.
 * This sidebar organizes the documentation to help users quickly find what they need.
 */
const sidebars: SidebarsConfig = {
    // Main documentation sidebar for Rhythmix
    rhythmixSidebar: [
        {
            type: 'doc',
            id: 'intro',
            label: 'Introduction',
        },
        {
            type: 'category',
            label: '🚀 Getting Started',
            collapsed: false,
            items: [
                'getting-started/installation',
                'getting-started/quick-start',
                'getting-started/basic-concepts',
            ],
        },
        {
            type: 'category',
            label: '📝 Expression Syntax',
            collapsed: false,
            items: [
                'expressions/overview',
                'expressions/comparison',
                'expressions/interval',
                'expressions/logical',
                {
                    type: 'category',
                    label: 'Functions',
                    items: [
                        'expressions/functions/count',
                        'expressions/functions/count-strict',
                    ],
                },
                {
                    type: 'category',
                    label: 'Chain Expressions',
                    items: [
                        'expressions/chain/overview',
                        'expressions/chain/filter',
                        'expressions/chain/limit',
                        'expressions/chain/window',
                        'expressions/chain/take',
                        'expressions/chain/calculators',
                        'expressions/chain/meet',
                    ],
                },
            ],
        },
        {
            type: 'category',
            label: '🔧 Advanced Features',
            collapsed: true,
            items: [
                'advanced/custom-filters',
                'advanced/custom-calculators',
                'advanced/custom-meet-functions',
                'advanced/state-transitions',
            ],
        },
        {
            type: 'category',
            label: '📚 API Reference',
            collapsed: true,
            items: [
                'api/rhythmix-event-data',
                'api/rhythmix-compiler',
                'api/rhythmix-executor',
            ],
        },
        {
            type: 'category',
            label: '💡 Examples & Use Cases',
            collapsed: true,
            items: [
                'examples/temperature-monitoring',
                'examples/production-quality',
                'examples/network-monitoring',
                'examples/sensor-data',
                'examples/financial-risk',
                'examples/medical-devices',
            ],
        },
        {
            type: 'category',
            label: '📖 Appendix',
            collapsed: true,
            items: [
                'appendix/comparison-examples',
                'appendix/interval-examples',
                'appendix/logical-examples',
                'appendix/best-practices',
                'appendix/faq',
            ],
        },
    ],

    // Tutorial sidebar (keeping the original for reference)
    tutorialSidebar: [{type: 'autogenerated', dirName: 'tutorial-basics'}],
};

export default sidebars;
